import Sidebar from "@/components/sidebar";
import { AuthProvider } from "@/context/authprovider";
import { ProjectProvider } from "@/context/projectProvider";
import { Suspense } from "react";
import Loading from "./loading";

export const metadata = {
    title: "User",
    description: "Generated by create next app",
  };
  
export default function UserLayout({ children }) {
    return (
        <section>
          <Suspense fallback={<Loading />}>
            {children}
          </Suspense>
        </section>
    );
}
  